# Generated by Django 5.2.1 on 2025-05-26 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classificacao', models.CharField(db_column='classificacao')),
                ('dica_imc', models.TextField(db_column='dica')),
            ],
            options={
                'db_table': 'dica',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='imc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_consulta', models.DateField(auto_now_add=True, db_column='data_consulta')),
                ('idade', models.IntegerField(db_column='idade')),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imc',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='imc_user_base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(db_column='nome', max_length=10)),
                ('idade', models.IntegerField(db_column='idade')),
                ('peso', models.FloatField(db_column='peso')),
                ('altura', models.FloatField(db_column='altura')),
                ('sexo', models.CharField(db_column='sexo', max_length=10)),
                ('imc_res', models.FloatField(blank=True, db_column='imc_res', null=True)),
                ('classificacao', models.CharField(blank=True, db_column='classificacao', max_length=30, null=True)),
                ('objetivo', models.CharField(db_column='objetivo', max_length=200)),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'imc_user_base',
                'ordering': ['id'],
            },
        ),
    ]
