# Generated by Django 5.2.1 on 2025-06-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_imc_data_consulta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(db_column='data')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'checklist',
                'ordering': ['-data'],
                'unique_together': {('id_usuario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(db_column='descricao')),
                ('done', models.BooleanField(db_column='done', default=False)),
                ('checklist', models.ForeignKey(db_column='id_checklist', on_delete=django.db.models.deletion.CASCADE, to='core.checklist')),
            ],
            options={
                'db_table': 'atividade',
                'ordering': ['id'],
            },
        ),
    ]
